name: CI

on: [ push, workflow_call ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: '18'

            -   uses: pnpm/action-setup@v3
                with:
                    version: 'latest'
                    run_install: true

            # no need to check this separately, see below
            #-   name: Run Build
            #    run: pnpm build

            # this includes a build + publint run
            -   name: Run Lint
                run: pnpm lint

            -   name: Run Tests
                run: pnpm test

