name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            -   uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   uses: pnpm/action-setup@v2
                with:
                    version: 'latest'
                    run_install: true

            -   name: Run Build
                run: pnpm build

            -   name: Run Tests
                run: pnpm test

            -   name: Run Lint
                run: pnpm lint

