name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   uses: actions/setup-node@v2-beta
                with:
                    node-version: '18'

            -   uses: pnpm/action-setup@v1.2.1
                with:
                    version: '^7'
                    run_install: true

            -   name: Run Build
                run: pnpm build

            -   name: Run Tests
                run: pnpm test

            -   name: Run Lint
                run: pnpm lint

