name: Release version to npm

on:
    workflow_dispatch:
    push:
        tags:
            - '*'

jobs:
    ci:
        uses: "./.github/workflows/ci.yml"
    deploy:
        name: deploy
        needs: [ci]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            -   uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   uses: pnpm/action-setup@v2
                with:
                    version: 'latest'
                    run_install: true

            -   name: Run Build
                run: pnpm build

            -   name: Publish package
                uses: JS-DevTools/npm-publish@v1
                with:
                    token: ${{ secrets.NPM_TOKEN }}
