name: Release version to npm

on:
    workflow_dispatch:
    push:
        tags:
            - '*'

jobs:
    ci:
        uses: ".github/workflows/ci.yml@latest"
    deploy:
        name: deploy
        needs: [ci]
        runs-on: ubuntu-latest
        steps:
            -   name: Test
                run: echo 'test'
