name: Release version to npm

on:
    workflow_dispatch:
    push:
        tags:
            - '*'

jobs:
    ci:
        uses: "./.github/workflows/ci.yml"
    deploy:
        name: deploy
        needs: [ci]
        runs-on: ubuntu-latest
        steps:
            -   uses: JS-DevTools/npm-publish@v1
                with:
                    token: ${{ secrets.NPM_TOKEN }}
